### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by dsyme** [nessos/Vagabond#10]
Got this when by MBrace scripting session had included some WPF and charting. Can give a full repro if needed.

```
#load "../../../FSharpDemoScripts/extlib/EventEx-0.1.fsx"
#load "../../../FSharpDemoScripts/packages/FSharp.Charting/FSharp.Charting.fsx"
#load "../../../FSharpDemoScripts/vizlib/load-wpf.fsx"
#load "../../../FSharpDemoScripts/vizlib/show.fsx"


Nessos.Vagabond.VagabondException: Found circular dependencies: PresentationFramework, ReachFramework, System.Printing.
   at Nessos.Vagabond.DependencyAnalysis.getAssemblyOrdering(FSharpList`1 dependencies) in c:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\SliceCompiler\DependencyAnalysis.fs:line 23
   at Nessos.Vagabond.DependencyAnalysis.traverseDependencies(FSharpFunc`2 ignoreF, Boolean requireLoaded, FSharpOption`1 state, IEnumerable`1 assemblies) in c:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\SliceCompiler\DependencyAnalysis.fs:line 107
   at MBrace.Azure.Runtime.Primitives.BlobAssemblyManager.ComputeDependencies[T](T graph) in C:\workspace\krontogiannis\MBrace.Azure\src\MBrace.Azure.Runtime\Primitives\BlobAssemblyManager.fs:line 193
   at <StartupCode$MBrace-Azure-Client>.$Client.CreateProcessAsync@240.Invoke(Unit unitVar) in C:\workspace\krontogiannis\MBrace.Azure\src\MBrace.Azure.Client\Client.fs:line 248
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@803.Invoke(AsyncParams`1 args)
   at MBrace.Core.Internals.ExceptionDispatchInfoUtils.Async.RunSync[T](FSharpAsync`1 workflow, FSharpOption`1 cancellationToken) in c:\Users\eirik\Development\mbrace\MBrace.Core\src\MBrace.Core\Utils\ExceptionDispatchInfo.fs:line 136
   at <StartupCode$FSI_0028>.$FSI_0028.main@() in C:\GitHub\dsyme\MBrace.StarterKit\azure\HandsOnTutorial\0-demo.fsx:line 79
```

**Comment by eiriktsarpalis** [comment]
Thanks, this has been fixed in the latest Vagabond.

**Comment by dsyme** [comment]
Great!  will upgrade my cluster (is it in MBrace.Azure 0.6.10?)

**Comment by eiriktsarpalis** [comment]
I'm afraid not. It'll probably take some time before this finds itself in MBrace.Azure.

**Comment by dsyme** [comment]
ok, no problem

BTW am happy to start to contribute to MBrace.Azure, e.g. to help things like this move along and help make releases - we can probably start to bring in more community people too. I know @krontogiannis has to do some army service! :)

**Comment by eiriktsarpalis** [comment]
Great, we'd be happy to have you!

**Comment by dsyme** [comment]
Could you add a DEVGUIDE.md that covers building, testing and releasing, and a CONTRIBUTING.md that covers contribution guidelines, to both MBrace.Azure and MBrace.Core?  

Ideally you want it so I or another contributor could build, test and make a release (assuming we have the keys to push packages and to the docs repo).

best
don
